eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  error:
    include-stacktrace: never
  port: 8101
spring:
  application:
    name: ibmshop-backend-products-api
  datasource:
    password: root
    url: jdbc:mysql://localhost/db_ibmshop_product?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  profiles:
    active: test
